### ISSUE TITLE
Temp .snmprec Directories Should be Deleted

### ISSUE THREAD

**Issue by belavina** [Seneca-CDOT/simengine#1]
Each `SNMPAgent` creates a temp directory containing `public.snmprec` file that stays after program exit & fills up the disk space.
See:  `SNMPAgent` in `einginecore/enginecore/state/assets.py`

**Comment by ctyler** [comment]
These can be deleted as soon as snmpsimd opens them. They'll stay alive until snmpsimd deletes them, then be freed.
